def defineTriggerList( year ):

    """ 
    by default returns a dict of triggers to be used for a given year, grouped in final states
    """

    #triggers of interest (here we list the main analysis triggers)
    ## paths for ee and mm are checked with https://twiki.cern.ch/twiki/bin/view/CMS/TopTrigger#HLT_Menus_in_Run_2
    ## J/Psi dimuon triggers are not used
    signal_trig_dict={
        2016: {'ajj'     : ['HLT_Photon75_R9Id90_HE10_Iso40_EBOnly_VBF'],
               'highpta' : ['HLT_Photon175'],
               'ee'      : ['HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ','HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf','HLT_Ele32_eta2p1_WPTight_Gsf','HLT_Ele27_WPTight_Gsf','HLT_Ele25_eta2p1_WPTight_Gsf'],
               'mm'      : ['HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ','HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ','HLT_IsoMu24','HLT_IsoTkMu24','HLT_IsoMu22_eta2p1','HLT_IsoTkMu22_eta2p1']},
        2017: {'ajj'     : ['HLT_Photon75_R9Id90_HE10_IsoM_EBOnly_PFJetsMJJ300DEta3'],
               'highpta' : ['HLT_Photon200'],
               'ee'      : ['HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL','HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ', 'HLT_Ele35_WPTight_Gsf', 'HLT_Ele38_WPTight_Gsf', 'HLT_Ele40_WPTight_Gsf', 'HLT_Ele32_WPTight_Gsf_L1DoubleEG'],
               'mm'      : ['HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ','HLT_IsoMu27','HLT_IsoMu24_eta2p1']},
        2018: {'ajj'     : ['HLT_Photon75_R9Id90_HE10_IsoM_EBOnly_PFJetsMJJ300DEta3'],
               'highpta' : ['HLT_Photon200'],
               'ee'      : ['HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL','HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ','HLT_Ele32_WPTight_Gsf'],
               'mm'      : ['HLT_IsoMu24']}
        }

    #here is the list of triggers, needed for either fake or trigger studies of the main categories
    ctrl_trig_dict={
        2018: {'ee': [   'HLT_Ele30_eta2p1_WPTight_Gsf_CentralPFJet35_EleCleaned',
                         'HLT_Ele38_WPTight_Gsf',
                         'HLT_Ele28_eta2p1_WPTight_Gsf_HT150',
                         'HLT_Ele32_WPTight_Gsf',
                         'HLT_Ele35_WPTight_Gsf'],
               'ajj': [   'HLT_PFJet400',
                          'HLT_PFJetFwd200',
                          'HLT_PFJetFwd450',
                          'HLT_PFJetFwd500',
                          'HLT_PFJet200',
                          'HLT_PFJet40',
                          'HLT_PFJet60',
                          'HLT_PFJet500',
                          'HLT_PFJetFwd260',
                          'HLT_PFJetFwd60',
                          'HLT_PFJetFwd140',
                          'HLT_PFJetFwd320',
                          'HLT_PFJet140',
                          'HLT_PFJet80',
                          'HLT_PFJetFwd40',
                          'HLT_PFJet550',
                          'HLT_PFJetFwd400',
                          'HLT_PFJetFwd80',
                          'HLT_PFJet320',
                          'HLT_PFJet450',
                          'HLT_PFJet260'],
               'mm': [   'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8',
                         'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8',
                         'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ'],
               'highpta': [   'HLT_Photon300_NoHE',
                              'HLT_Photon90',
                              'HLT_Photon165_R9Id90_HE10_IsoM',
                              'HLT_Photon250_NoHE',
                              'HLT_Photon50_R9Id90_HE10_Iso40_EBOnly_VBF',
                              'HLT_Photon50_R9Id90_HE10_IsoM',
                              'HLT_Photon165_HE10',
                              'HLT_Photon90_R9Id90_HE10_Iso40_EBOnly_VBF',
                              'HLT_Photon75',
                              'HLT_Photon75_R9Id90_HE10_IsoM_EBOnly_PFJetsMJJ600DEta3',
                              'HLT_Photon90_R9Id90_HE10_IsoM',
                              'HLT_Photon36_R9Id90_HE10_Iso40_EBOnly_VBF',
                              'HLT_Photon75_R9Id90_HE10_IsoM',
                              'HLT_Photon36_R9Id90_HE10_IsoM',
                              'HLT_Photon50',
                              'HLT_Photon175',
                              'HLT_Photon120',
                              'HLT_Photon120_R9Id90_HE10_Iso40_EBOnly_VBF',
                              'HLT_Photon120_R9Id90_HE10_IsoM',
                              'HLT_Photon75_R9Id90_HE10_Iso40_EBOnly_VBF',
                              'HLT_Photon36']},
        2017:{'ee': [   'HLT_Ele30_eta2p1_WPTight_Gsf_CentralPFJet35_EleCleaned',
                        'HLT_Ele38_WPTight_Gsf',
                        'HLT_Ele28_eta2p1_WPTight_Gsf_HT150',
                        'HLT_Ele32_WPTight_Gsf',
                        'HLT_Ele35_WPTight_Gsf',
                        'HLT_Ele40_WPTight_Gsf',
                        'HLT_Ele32_WPTight_Gsf_L1DoubleEG'],
              'ajj': [   'HLT_PFJet400',
                         'HLT_PFJetFwd200',
                         'HLT_PFJetFwd450',
                         'HLT_PFJetFwd500',
                         'HLT_PFJet200',
                         'HLT_PFJet40',
                         'HLT_PFJet60',
                         'HLT_PFJet500',
                         'HLT_PFJetFwd260',
                         'HLT_PFJetFwd60',
                         'HLT_PFJetFwd140',
                         'HLT_PFJetFwd320',
                         'HLT_PFJet140',
                         'HLT_PFJet80',
                         'HLT_PFJet550',
                         'HLT_PFJetFwd40',
                         'HLT_PFJetFwd400',
                         'HLT_PFJetFwd80',
                         'HLT_PFJet320',
                         'HLT_PFJet450',
                         'HLT_PFJet260'],
              'mm': ['HLT_IsoMu24', 'HLT_IsoMu24_eta2p1'],
              'highpta': [   'HLT_Photon50_R9Id90_HE10_IsoM',
                             'HLT_Photon75_R9Id90_HE10_IsoM_EBOnly_PFJetsMJJ600DEta3',
                             'HLT_Photon90_R9Id90_HE10_IsoM',
                             'HLT_Photon75_R9Id90_HE10_IsoM',
                             'HLT_Photon175',
                             'HLT_Photon150']},
        2016:{'ee': [   'HLT_Ele32_eta2p1_WPTight_Gsf',
                        'HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf'],
              'ajj': [   'HLT_PFJet400',
                         'HLT_PFJet200',
                         'HLT_PFJet40',
                         'HLT_PFJet60',
                         'HLT_PFJet500',
                         'HLT_PFJet140',
                         'HLT_PFJet80',
                         'HLT_PFJet320',
                         'HLT_PFJet450',
                         'HLT_PFJet260'],
              'mm': [   'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL',
                        'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL',
                        'HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ',
                        'HLT_IsoMu24_eta2p1',
                        'HLT_IsoTkMu24_eta2p1',
                        'HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL'],
              'highpta': [   'HLT_Photon300_NoHE',
                             'HLT_Photon90',
                             'HLT_Photon165_R9Id90_HE10_IsoM',
                             'HLT_Photon250_NoHE',
                             'HLT_Photon50_R9Id90_HE10_Iso40_EBOnly_VBF',
                             'HLT_Photon50_R9Id90_HE10_IsoM',
                             'HLT_Photon165_HE10',
                             'HLT_Photon90_R9Id90_HE10_Iso40_EBOnly_VBF',
                             'HLT_Photon75',
                             'HLT_Photon90_R9Id90_HE10_IsoM',
                             'HLT_Photon36_R9Id90_HE10_Iso40_EBOnly_VBF',
                             'HLT_Photon75_R9Id90_HE10_IsoM',
                             'HLT_Photon36_R9Id90_HE10_IsoM',
                             'HLT_Photon50',
                             'HLT_Photon120',
                             'HLT_Photon120_R9Id90_HE10_Iso40_EBOnly_VBF',
                             'HLT_Photon120_R9Id90_HE10_IsoM',
                             'HLT_Photon36']}
        }



    
    return signal_trig_dict[year],ctrl_trig_dict[year]
